baseURL: "https://elkspass.sickendick.com/"
languageCode: "en-us"
title: "Elks Pass Sickendick Home"
theme: hugo-geekdoc
#googleAnalytics:

pygmentsUseClasses: true
pygmentsCodeFences: true
disablePathToLower: true 
enableGitInfo: true

taxonomies:
  tag: tags

params:
  description: "A reference wiki for the Sickendick Elks Pass home"
  geekdocLogo: "home.svg"
  geekdocRepo: "https://github.com/kc0bfv/elkspass.sickendick.com"
  geekdocEditPath: "edit/main/content"
  geekdocListUseTOC: true
